[
   "█▀▄▀█ █▀█ ▀█▀ █▀█ █▀▄▀█ ▀▄▀ ▀▄▀ ▀▄▀\n\n█░▀░█ █▀▄ ░█░ █▄█ █░▀░█ █░█ █░█ █░█",
   "Owner dark devil",
   "FaceBook: https://www.facebook.com/100092968814324",
   "▒█▀▄▀█ ▀▀█▀▀ ▀▄▒▄▀ \n\n▒█▒█▒█ ░▒█░░ ░▒█░░ \n\n▒█░░▒█ ░▒█░░ ▄▀▒▀▄ \n\n -\n\n▒█▀▀█ █▀▀█ █▀▀█ ░░▀ █▀▀ █▀▀ ▀▀█▀▀ \n\n▒█▄▄█ █▄▄▀ █░░█ ░░█ █▀▀ █░░ ░░█░░ \n\n▒█░░░ ▀░▀▀ ▀▀▀▀ █▄█ ▀▀▀ ▀▀▀ ░░▀░░",
   "MrTomXxX  Version 2 Final update. Subscribe On YouTube"
]
